name: Run PHP CodeSniffer

# Run PHPCBF to fix changes then PHPCS with GitHubActionsAnnotations report
# https://github.com/squizlabs/PHP_CodeSniffer/pull/2918
#
# NB: Pull requests from forks do not have access to repository secrets so cannot commit changes.
#
# @author BrianHenryIE

on:
  push:
    branches:
      - master

jobs:
  php-codesniffer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: cs2pr

      - name: Run Composer install
        uses: php-actions/composer@v6

      - name: Run PHPCBF to fix what it can
        continue-on-error: true
        run: vendor/bin/phpcbf

      - name: Commit PHPCBF changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: "ðŸ¤– PHPCBF"

      - name: Run PHPCS to add annotations to the commit
        continue-on-error: true
        run: vendor/bin/phpcs -q -n --report=checkstyle | cs2pr
